Rp2040 Target Support
lf-lang/reactor-c pull request #253
Opened 2023-07-21 18:53 UTC by gundralaa

Basic unthreaded runtime support for rp2040 target.
Uses the pico-sdk as a dependency and utilizes the high level time library to provide timer support.

2023-07-21 22:08 UTC, petervdonovan commented on core/platform/lf_rp2040_support.c
> + * called first and that lf_critical_section_exit() is called later.
```suggestion
 * called first and that lf_enable_critical_section_exit() is called later.
```

Is this what you meant (I'm not sure)? It seems like the function that has to be called later should modify `_lf_num_nested_critical_sections`.

2023-07-21 22:08 UTC, petervdonovan commented on core/platform/lf_rp2040_support.c
> + * TODO: needs to be used sparingly, find a better way for event queue
All of these TODOs are basically the same as FIXMEs in that they probably should be moved out of the code and into GitHub issues before this is merged.

2023-07-24 09:32 UTC, edwardalee requested changes
This looks pretty good, but the functions defined need comments. E.g., _lf_clock_now should state that it return the time since boot in nanoseconds.  Note that by convention, comments consist of full sentences with proper punctuation and javadoc style annotations. So, for _lf_clock_now, it should be:

```
/**
 * Write the time since boot in nanoseconds into the variable pointed to by the argument and return 0.
 * @param t Pointer to the variable to write to.
 */

Note the use of the imperative case above. I.e., don't say this:

```
 * Writes the time since boot in nanoseconds into the variable pointed to by the argument and return 0.
```

The above is not a sentence in English.

2023-07-24 20:42 UTC, gundralaa commented on core/CMakeLists.txt
> +    endif()
Removed and added validator implementations for RP2040 that disallows threads for now until the threaded runtime is included to lingua-franca pr checklist.

2023-07-24 20:43 UTC, gundralaa commented on core/platform/lf_rp2040_support.c
> + * Uses the pico-sdk which targets the lower level peripheral layer.
changed

2023-07-25 21:48 UTC, lhstrh approved these changes

2023-07-26 02:29 UTC, merged